apiVersion: v1
kind: Service
metadata:
  name: grade-submission-api
spec:
  type: ClusterIP
  # ClusterIP is the default type, which exposes the service on a cluster-internal IP
  selector:
    app.kubernetes.io/instance: grade-submission-api
  ports:
  - port: 3000
    targetPort: 3000
