apiVersion: v1
kind: Pod
metadata:
  name: grade-submission-portal
  labels:
    app.kubernetes.io/name: grade-submission
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: grade-submission-portal
spec:
  containers:
  - name: grade-submission-portal
    image: rslim087/kubernetes-course-grade-submission-portal:latest
    resources:
    #requests is the minimum amount of resources required for the container
    #limits is the maximum amount of resources that can be used by the container
      requests: 
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "256Mi"
    ports:
      - containerPort: 5001
